/**
 * Public surface of the engine data layer.
 *
 * Everything exported here is browser-safe: the zod contract mirrors, the
 * error taxonomy, and the react-query layer that talks to the /api/engine
 * proxy. Server-only pieces have their own entry points on purpose:
 *
 * - `@/lib/engine/client` — the typed client that calls the engine over
 *   HTTP (reads ENGINE_URL; route handlers + server components only).
 * - `@/lib/engine/proxy` — the route-handler wrapper used under
 *   app/api/engine/.
 */
export {
  EngineHttpError,
  EngineOfflineError,
  EngineValidationError,
  engineErrorMessage,
  isEngineError,
  isEngineOffline,
} from "./errors"
export {
  approveIntervention,
  capabilitiesQuery,
  capabilityQuery,
  engineKeys,
  engineStatusQuery,
  fetchCapabilities,
  fetchCapability,
  fetchEngineStatus,
  fetchIntervention,
  fetchInterventions,
  fetchRun,
  fetchRunEvidence,
  fetchRuns,
  fetchSessionState,
  interventionQuery,
  interventionsQuery,
  markCapabilityReviewed,
  postSessionAction,
  rejectIntervention,
  requestApproval,
  runEvidenceQuery,
  runQuery,
  runsQuery,
  sessionStateQuery,
  startDiscovery,
  startReplay,
} from "./queries"
export {
  connectEngineControl,
  ENGINE_WS_URL,
  type ControlCommand,
  type EngineControlMessage,
} from "./ws"
export {
  artifactVersionSchema,
  businessOutcomeSchema,
  capabilityArtifactSchema,
  capabilityInputSchema,
  capabilityOutputSchema,
  capabilityStepSchema,
  checkpointSchema,
  controlLogEntrySchema,
  decideInterventionBodySchema,
  discoverRequestSchema,
  discoveryResultSchema,
  engineCapabilityRowSchema,
  engineCapabilitySchema,
  engineCapabilitySummarySchema,
  engineErrorBodySchema,
  engineEvidenceSchema,
  engineHealthSchema,
  engineInterventionRowSchema,
  engineInterventionSchema,
  engineRunResultSchema,
  engineRunRowSchema,
  engineRunSchema,
  interventionContextSchema,
  locatorSchema,
  parseCapabilityArtifact,
  rejectInterventionResponseSchema,
  approveInterventionResponseSchema,
  replayRequestSchema,
  requestApprovalBodySchema,
  requestApprovalResponseSchema,
  reviewCapabilityResponseSchema,
  riskClassSchema,
  runBusinessOutcomeSchema,
  runHardFailureSchema,
  runRecoverableSchema,
  runResultSchema,
  runStatusSchema,
  runSuccessSchema,
  sessionActionBodySchema,
  sessionActionResponseSchema,
  sessionStateSchema,
  startRunResponseSchema,
  stepActionSchema,
  stepEvidenceSchema,
  targetSchema,
  type ApproveInterventionResponse,
  type ArtifactVersion,
  type BusinessOutcome,
  type CapabilityArtifact,
  type CapabilityInput,
  type CapabilityOutput,
  type CapabilityStep,
  type Checkpoint,
  type ControlLogEntry,
  type DecideInterventionBody,
  type DiscoverRequest,
  type DiscoveryResult,
  type EngineCapability,
  type EngineCapabilityRow,
  type EngineCapabilitySummary,
  type EngineEvidence,
  type EngineHealth,
  type EngineIntervention,
  type EngineInterventionRow,
  type EngineRun,
  type EngineRunResult,
  type EngineRunRow,
  type InterventionContext,
  type Locator,
  type RejectInterventionResponse,
  type ReplayRequest,
  type RequestApprovalBody,
  type RequestApprovalResponse,
  type ReviewCapabilityResponse,
  type RiskClass,
  type RunBusinessOutcome,
  type RunHardFailure,
  type RunRecoverable,
  type RunResult,
  type RunStatus,
  type RunSuccess,
  type SessionActionBody,
  type SessionActionResponse,
  type SessionState,
  type StartRunResponse,
  type StepAction,
  type StepEvidence,
  type Target,
} from "./schemas"
