/**
 * Public surface of the engine data layer.
 *
 * Everything exported here is browser-safe: the zod contract mirrors, the
 * error taxonomy, and the react-query layer that talks to the /api/engine
 * proxy. Server-only pieces have their own entry points on purpose:
 *
 * - `@/lib/engine/client` — the typed client that calls the engine over
 *   HTTP (reads ENGINE_URL; route handlers + server components only).
 * - `@/lib/engine/proxy` — the route-handler wrapper used under
 *   app/api/engine/.
 */
export {
  EngineHttpError,
  EngineOfflineError,
  EngineValidationError,
  engineErrorMessage,
  isEngineError,
  isEngineOffline,
} from "./errors"
export {
  approveIntervention,
  capabilitiesQuery,
  capabilityQuery,
  engineKeys,
  engineStatusQuery,
  fetchCapabilities,
  fetchCapability,
  fetchEngineStatus,
  fetchInterventions,
  fetchRun,
  fetchRunEvidence,
  fetchRuns,
  interventionsQuery,
  markCapabilityReviewed,
  rejectIntervention,
  runEvidenceQuery,
  runQuery,
  runsQuery,
  startDiscovery,
  startReplay,
} from "./queries"
export {
  artifactVersionSchema,
  businessOutcomeSchema,
  capabilityArtifactSchema,
  capabilityInputSchema,
  capabilityOutputSchema,
  capabilityStepSchema,
  checkpointSchema,
  discoverRequestSchema,
  discoveryResultSchema,
  engineCapabilityRowSchema,
  engineCapabilitySchema,
  engineCapabilitySummarySchema,
  engineErrorBodySchema,
  engineEvidenceSchema,
  engineHealthSchema,
  engineInterventionRowSchema,
  engineInterventionSchema,
  engineRunResultSchema,
  engineRunRowSchema,
  engineRunSchema,
  locatorSchema,
  parseCapabilityArtifact,
  rejectInterventionResponseSchema,
  approveInterventionResponseSchema,
  replayRequestSchema,
  reviewCapabilityResponseSchema,
  riskClassSchema,
  runBusinessOutcomeSchema,
  runHardFailureSchema,
  runRecoverableSchema,
  runResultSchema,
  runStatusSchema,
  runSuccessSchema,
  startRunResponseSchema,
  stepActionSchema,
  stepEvidenceSchema,
  targetSchema,
  type ApproveInterventionResponse,
  type ArtifactVersion,
  type BusinessOutcome,
  type CapabilityArtifact,
  type CapabilityInput,
  type CapabilityOutput,
  type CapabilityStep,
  type Checkpoint,
  type DiscoverRequest,
  type DiscoveryResult,
  type EngineCapability,
  type EngineCapabilityRow,
  type EngineCapabilitySummary,
  type EngineEvidence,
  type EngineHealth,
  type EngineIntervention,
  type EngineInterventionRow,
  type EngineRun,
  type EngineRunResult,
  type EngineRunRow,
  type Locator,
  type RejectInterventionResponse,
  type ReplayRequest,
  type ReviewCapabilityResponse,
  type RiskClass,
  type RunBusinessOutcome,
  type RunHardFailure,
  type RunRecoverable,
  type RunResult,
  type RunStatus,
  type RunSuccess,
  type StartRunResponse,
  type StepAction,
  type StepEvidence,
  type Target,
} from "./schemas"
